### ISSUE TITLE
Missing subject filters

### ISSUE THREAD

**Issue by trollodel** [Chris1101/ArgoMarksGraph#4]
There are too many subject and it's difficult to follow a subject graph

**Comment by creeloper27** [comment]
I sudgest highlighting the subject name when you hover the mouse on the corrisponding line in the graph.

**Comment by trollodel** [comment]
@creeloper27 No please, your suggest is awful.   
@Chris1101 must think to a solve this problem

**Comment by Chris1101** [comment]
@trollodel I'm working on it

**Comment by creeloper27** [comment]
It would be much cooler with the feature i suggested :D

**Comment by trollodel** [comment]
@creeloper27 if you think your solution is better, fork the repo and create this feature, then send a pull request and @Chris1101 decides for your code.

**Comment by creeloper27** [comment]
I don't program in Python, just C# for now

**Comment by trollodel** [comment]
so, If you don't program in python, you can't know the problems with coding similar function.

**Comment by creeloper27** [comment]
@trollodel I saied that i don't program in python, but i know the basic functions.

**Comment by Chris1101** [comment]
Implemented.
